default_language_version:
    python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-ast
      - id: end-of-file-fixer
        exclude: "requirements"
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: "requirements"
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0 # flake8
    hooks:
      - id: flake8
        args: ["--ignore=E501,E402,E127,F403,F405,E203,W503", "--count"]
        exclude: "requirements|development|developer"
  - repo: https://github.com/ambv/black
    rev: 23.9.1 # black
    hooks:
      - id: black
        language_version: python3.11
        args: ["--line-length=119"]
        exclude: "requirements|development|developer"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0 # isort
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=119"]
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python test_all_devices.py
        language: system
        types: [python]
