"""
    * SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
    * SPDX-License-Identifier: Apache-2.0
"""
from typing import Final

API_KEY: Final[str] = "v6GFvkweNo7DK7yD3ylIZ9w52aKBU0eJ7wLXkSR3"
CLIENT_PREFIX: Final[str] = "thinq-open"


# Device Type
class DeviceType:
    AIR_CONDITIONER = "DEVICE_AIR_CONDITIONER"
    SYSTEM_BOILER = "DEVICE_SYSTEM_BOILER"
    AIR_PURIFIER = "DEVICE_AIR_PURIFIER"
    DISH_WASHER = "DEVICE_DISH_WASHER"
    DRYER = "DEVICE_DRYER"
    OVEN = "DEVICE_OVEN"
    REFRIGERATOR = "DEVICE_REFRIGERATOR"
    ROBOT_CLEANER = "DEVICE_ROBOT_CLEANER"
    WASHER = "DEVICE_WASHER"
    STYLER = "DEVICE_STYLER"
    WATER_PURIFIER = "DEVICE_WATER_PURIFIER"
    HOOD = "DEVICE_HOOD"
    COOKTOP = "DEVICE_COOKTOP"
    DEHUMIDIFIER = "DEVICE_DEHUMIDIFIER"
    HUMIDIFIER = "DEVICE_HUMIDIFIER"
    MICROWAVE_OVEN = "DEVICE_MICROWAVE_OVEN"
    WINE_CELLAR = "DEVICE_WINE_CELLAR"
    CEILING_FAN = "DEVICE_CEILING_FAN"
    WATER_HEATER = "DEVICE_WATER_HEATER"
    KIMCHI_REFRIGERATOR = "DEVICE_KIMCHI_REFRIGERATOR"
    WASHTOWER_WASHER = "DEVICE_WASHTOWER_WASHER"
    WASHTOWER_DRYER = "DEVICE_WASHTOWER_DRYER"
    WASHTOWER = "DEVICE_WASHTOWER"
    STICK_CLEANER = "DEVICE_STICK_CLEANER"
    HOME_BREW = "DEVICE_HOME_BREW"
    AIR_PURIFIER_FAN = "DEVICE_AIR_PURIFIER_FAN"
    PLANT_CULTIVATOR = "DEVICE_PLANT_CULTIVATOR"
    WASHCOMBO_MAIN = "DEVICE_WASHCOMBO_MAIN"
    WASHCOMBO_MINI = "DEVICE_WASHCOMBO_MINI"


PROPERTY_READABLE: Final[str] = "r"
PROPERTY_WRITABLE: Final[str] = "w"
